name: Flutter All Platforms CI

on:
  push:
    branches: ["main", "uzair-dev"]
  pull_request:
    branches: ["main"]

jobs:
  # Android and Web Build (Ubuntu runner)
  build-android-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze and test
        run: |
          flutter analyze
          flutter test

      # Android Builds
      - name: Build Android APKs
        run: flutter build apk --release --split-per-abi

      - name: Build Android App Bundle
        run: flutter build appbundle --release

      # Web Build
      - name: Build Web
        run: |
          flutter config --enable-web
          flutter build web --release

      # Upload Android artifacts
      - name: Upload Android APKs
        uses: actions/upload-artifact@v4
        with:
          name: android-builds
          path: |
            build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            build/app/outputs/flutter-apk/app-x86_64-release.apk
            build/app/outputs/bundle/release/app-release.aab

      # Upload Web artifacts
      - name: Upload Web
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

  # iOS Build (requires macOS)
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # iOS Build
      - name: Build iOS
        run: |
          flutter config --enable-ios
          flutter build ios --release --no-codesign

      # Upload iOS artifacts
      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos

  # macOS Build
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # macOS Build
      - name: Build macOS
        run: |
          flutter config --enable-macos-desktop
          flutter build macos --release

      # Upload macOS artifacts
      - name: Upload macOS Build
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: build/macos/Build/Products/Release

  # Windows Build
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # Windows Build
      - name: Build Windows
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --release

      # Upload Windows artifacts
      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/x64/runner/Release

  # Linux Build
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libgtk-3-dev

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.4"
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # Linux Build
      - name: Build Linux
        run: |
          flutter config --enable-linux-desktop
          flutter build linux --release

      # Upload Linux artifacts
      - name: Upload Linux Build
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: build/linux/x64/release/bundle
